# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students (6d0e6d2e-cd5a-4f3e-b17a-afc9bce653dc)'
    appType: 'webAppLinux'
    appName: 'webrres'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
